resources:
  - stateful-set.yaml
  - service-dns.yaml
  - service-web.yaml
  - service-headless.yaml

namespace: pihole

labels:
  - pairs:
      app: pihole
    includeTemplates: true
    includeSelectors: true

configMapGenerator:
  - name: pihole-dnsmasq
    files:
      - config/01-pihole.conf

generatorOptions:
  disableNameSuffixHash: true
